version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: pollsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"


  web:
    build: .
    command: >
      sh -c "cd polls/ &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py loaddata fixtures/initial_data.json &&
             uwsgi --ini uwsgi.ini"
    environment:
      SECRET_KEY: mysecretkey
      POSTGRES_DB: pollsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8000:8000"
    depends_on:
      - "db"
   #     condition: service_healthy
    volumes:
      - .:/code
      - static_volume:/code/static

volumes:
  db_data:
  static_volume:
