apiVersion: v1
kind: Service
metadata:
  labels:
    appname: db
  name: db
spec:
  ports:
    - name: "{{ .Values.db.port }}"
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
  selector:
    appname: db
status:
  loadBalancer: {}
