apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: {{ .Values.djangoapp.managedIdentity }}
  labels:
    azure.workload.identity/use: "true"
  name: "id-djangoapp-test-sa"
  namespace: "default"